apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nahomy-c2

resources:
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app: nahomy-c2
  managed-by: kustomize

images:
  - name: nahomy-c2-api
    newName: nahomy-c2-api
    newTag: latest
