apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nahomy-c2-postgres-pvc
  labels:
    app: nahomy-c2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nahomy-c2-rabbitmq-pvc
  labels:
    app: nahomy-c2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
