apiVersion: v1
kind: Secret
metadata:
  name: nahomy-c2-secret
  labels:
    app: nahomy-c2
type: Opaque
stringData:
  DB_PASSWORD: 'nahomy_secret'
  JWT_SECRET: 'nahomy-c2-secret-key-change-in-production'
